branch-defaults:
  master:
    environment: jessie2-dev
    group_suffix: null
global:
  application_name: jessie2
  default_ec2_keyname: jessica-keypair
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
